import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;


const prod = (process.argv[2] === 'production');

let targetDir;
try {
	const localConfig = JSON.parse(fs.readFileSync('local.config.json', 'utf8'));
	targetDir = localConfig.targetDir;
} catch (e) {
	console.log('No local.config.json found or invalid. Skipping copy to vault.');
}

const copyPlugin = {
	name: 'copy-to-vault',
	setup(build) {
		if (!targetDir) return;

		build.onEnd(() => {
			if (!fs.existsSync(targetDir)) {
				fs.mkdirSync(targetDir, { recursive: true });
			}
			try {
				fs.copyFileSync('main.js', path.join(targetDir, 'main.js'));
				fs.copyFileSync('manifest.json', path.join(targetDir, 'manifest.json'));
				if (fs.existsSync('styles.css')) {
					fs.copyFileSync('styles.css', path.join(targetDir, 'styles.css'));
				}
				console.log(`Plugin built and copied to ${targetDir}`);
			} catch (e) {
				console.error("Failed to copy files:", e);
			}
		});
	},
};

esbuild.build({
	banner: {
		js: banner,
	},
	plugins: [copyPlugin],
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
}).catch(() => process.exit(1));
